version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - ./:/var/www/html
            - ./storage/app/public:/var/www/html/public/storage
            - ./vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        working_dir: /var/www/html
        links:
            - app
    app:
        build:
            context: ./
        volumes:
            - ./:/var/www/html
            - ./crontab:/etc/cron.d/cron
        working_dir: /var/www/html
        links:
            - redis
            #- mssql
    #mssql:
    #    image: microsoft/mssql-server-linux
    #    ports:
    #        - "1433:1433"
    #    volumes:
    #         - ./dbdata:/var/opt/mssql
    #    environment:
    #      SA_PASSWORD: "SA_PASSWORD"
    #      ACCEPT_EULA: "Y"
    #    container_name: mssql
    redis:
        image: redis:alpine3.8
        ports:
          - "6379:6379"